-- -- 创建班级信息表外键
ALTER TABLE class_info ADD CONSTRAINT CLASS_INFO_FK_TEACHERS_ID FOREIGN KEY (TEACHERS_ID) REFERENCES TEACHERS(ID);

-- -- 创建学生班级关系表外键
ALTER TABLE class_relation ADD CONSTRAINT CLASS_RELATION_FK_CLASS_INFO_ID FOREIGN KEY (CLASS_INFO_ID) REFERENCES CLASS_INFO(ID);
ALTER TABLE class_relation ADD CONSTRAINT CLASS_RELATION_FK_STUDENTS_ID FOREIGN KEY (STUDENTS_ID) REFERENCES STUDENTS(ID);
ALTER TABLE class_relation ADD CONSTRAINT CLASS_RELATION_FK_COLLEGE_ID FOREIGN KEY (COLLEGE_ID) REFERENCES COLLEGE(ID);

-- -- 创建学院信息表外键
ALTER TABLE college ADD CONSTRAINT COLLEGE_FK_CLASS_INFO_ID FOREIGN KEY (CLASS_INFO_ID) REFERENCES CLASS_INFO(ID);

-- -- 创建教师信息表外键
ALTER TABLE teachers ADD CONSTRAINT TEACHERS_FK_COLLEGE_ID FOREIGN KEY (COLLEGE_ID) REFERENCES COLLEGE(ID);
ALTER TABLE teachers ADD CONSTRAINT TEACHERS_FK_JOB_TITLE_ID FOREIGN KEY (JOB_TITLE_ID) REFERENCES JOB_TITLE(ID);

-- -- 创建学生信息表外键
ALTER TABLE students ADD CONSTRAINT STUDENTS_FK_ROOM_ID FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID);
ALTER TABLE students ADD CONSTRAINT STUDENTS_FK_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID);


-- -- 删除外键
-- ALTER TABLE class_info DROP FOREIGN KEY CLASS_INFO_FK_TEACHERS_ID;
--
-- ALTER TABLE class_relation DROP FOREIGN KEY CLASS_RELATION_FK_CLASS_INFO_ID;
-- ALTER TABLE class_relation DROP FOREIGN KEY CLASS_RELATION_FK_STUDENTS_ID;
-- ALTER TABLE class_relation DROP FOREIGN KEY CLASS_RELATION_FK_COLLEGE_ID;
--  
-- ALTER TABLE college DROP FOREIGN KEY COLLEGE_FK_CLASS_INFO_ID;
-- 
-- ALTER TABLE teachers DROP FOREIGN KEY TEACHERS_FK_COLLEGE_ID;
-- ALTER TABLE teachers DROP FOREIGN KEY TEACHERS_FK_JOB_TITLE_ID;
-- 
-- ALTER TABLE students DROP FOREIGN KEY STUDENTS_FK_ROOM_ID;
-- ALTER TABLE students DROP FOREIGN KEY STUDENTS_FK_ACCOUNT_ID;

